## Pandas 기초연습문제

In [1]:

import pandas as pd
#import함수로 pandas불러오기

1. 딕셔너리를 이용하여 아래와 같은 모양이 되도록 data frame을 생성하시오.


In [2]:
score={'학번':[201524213,201621223,201621233, 201611111, 201722222],
       '이름':['오지환','박용택','정성훈', '다니엘', '지민'],
       '학과':['경영정보','경영정보','경영정보','컴퓨터공학','컴퓨터공학'],
       'Quiz':[15,20,10,17,18],
       '중간고사':[20,20,15,18,16]}
# []로 리스트를 만들어 주고 {}딕셔너리 생성
df= pd.DataFrame(score) #df라는 데이터 프레임 생성
df

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
2  201621233  정성훈   경영정보    10    15
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16

In [3]:
df['학번'] #df에서 학번 리스트 안의 내용 추출

0    201524213
1    201621223
2    201621233
3    201611111
4    201722222
Name: 학번, dtype: int64

2. 위에서 생성한 데이터프레임으로부터 인덱싱을 이용하여 이름과 중간고사를 추출하시오.

In [4]:
df[['이름', '중간고사']] #df에서 이름과 중간고사를 표로 추출

이름  중간고사
0  오지환    20
1  박용택    20
2  정성훈    15
3  다니엘    18
4   지민    16

3. reindex를 이용하여 2, 0, 4, 1, 3 순으로 순서를 변경하시오.

In [5]:
df = df.reindex([2, 0, 4, 1, 3]) #reindex는 재색인으로 index를 변경하고  싶을때 쓴다, row column전부 변경가능

4. iloc과 loc을 각각 이용하여 박용택 학생의 record를 추출하시오. (iloc으로 한번, loc으로 한번 수행)

In [6]:
print(df.iloc[3]) #iloc[position] : 위치 정수 기반 인덱싱, [3]은 0부터 시작하므로 4번째 순서에 있는 박용택의 정보가 나타남
print(df.loc[1])#.loc[lable]: lable기반 인덱싱, 라벨 1이 박용택이므로 박용택의 정보가 추출됨. 

학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object
학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object


5. iloc과 loc을 각각 이용하여 모든 학생의 이름과 중간고사 점수를 추출하시오. (iloc으로 한번, loc으로 한번 수행)

In [7]:
print(df.iloc[:, [1, 4]]) # 행 전체중에 1번째와 4번째 열 추출
print(df.loc[:, ['이름', '중간고사']]) # 행 전체중에 이름과 중간고사 열 추출

    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18
    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18


6. 중간고사 점수의 평균을 구하시오.

In [8]:
df['중간고사'].mean() #중간고사 열의 평균을 구합니다.

17.8

7. 중간고사 점수가 가장 낮은 학생의 index를 구하시오.

In [9]:
df['중간고사'].idxmin() #idxmin : 최소값을 가지는 index레이블을 추출한다.

2

8. 퀴즈 점수가 가장 높은 학생의 학번을 구하시오.

In [10]:
df.loc[df['Quiz'].idxmax(), '학번']
#df.loc[df['Quiz'].idxmax()]['학번'] quoz중에 최소값을 가지는 학번 추출한다.

201621223

9. 위 데이터프레임의 각 열에 대해서 개수, 평균, 표준편차, 최소최대값 등의 다양한 통계량을 출력하시오.


In [11]:
df.describe() # 기술 통계량 출력

학번       Quiz       중간고사
count  5.000000e+00   5.000000   5.000000
mean   2.016200e+08  16.000000  17.800000
std    7.018995e+04   3.807887   2.280351
min    2.015242e+08  10.000000  15.000000
25%    2.016111e+08  15.000000  16.000000
50%    2.016212e+08  17.000000  18.000000
75%    2.016212e+08  18.000000  20.000000
max    2.017222e+08  20.000000  20.000000

10. 위 데이터프레임을 중간고사 점수에 따라 내림차순으로 정렬하시오.

In [12]:
df.sort_values('중간고사', ascending=False) #DataFrame.sort_value():내림차순 정리, 중간고사 기준, ascending(오름차순)=false

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16
2  201621233  정성훈   경영정보    10    15

11. 학생 중에서 퀴즈 점수가 평균 이상인 학생들의 이름을 출력하시오.

In [13]:
quiz_mean = df['Quiz'].mean() #quiz_mean에 dataframe에 이전 dataframe의 평균을 구한것을 할당.
df[df['Quiz'] > quiz_mean]['이름'] #평균보다 quiz점수가 높으면 이름 추출.

4     지민
1    박용택
3    다니엘
Name: 이름, dtype: object

12. 학생 중에서 퀴즈와 중간고사 점수 모두 평균 이상인 학생들의 record를 출력하시오.

In [14]:
quiz_mean = df['Quiz'].mean() #퀴즈 평균
mid_mean = df['중간고사'].mean() # 중간고사 평균
df[(df['Quiz'] > quiz_mean) & (df['중간고사'] > mid_mean)] #퀴즈 &(and) 중간고사가 두개다 평균이상인것만 추출.

학번   이름     학과  Quiz  중간고사
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

13. value_counts를 이용하여 학과 별로 학생의 수를 구하시오.

In [15]:
df['학과'].value_counts() #학과 value가 몇개 있는지 추출

경영정보     3
컴퓨터공학    2
Name: 학과, dtype: int64

14. groupby를 이용하여 학과 별로 중간고사의 평균을 구하시오.

In [16]:
df.groupby('학과')['중간고사'].mean() #group by: 특정컬럼을 그룹화함. .mean을 썼기 때문에 학과별 중간고사 평균을 그룹화한다.

학과
경영정보     18.333333
컴퓨터공학    17.000000
Name: 중간고사, dtype: float64

In [17]:
df.mean() #dataframe 평균.

학번      201620000.4
Quiz           16.0
중간고사           17.8
dtype: float64

In [18]:
list(df.groupby('학과')) #dataframe을 학과별로 그룹화

[('경영정보',
            학번   이름    학과  Quiz  중간고사
  2  201621233  정성훈  경영정보    10    15
  0  201524213  오지환  경영정보    15    20
  1  201621223  박용택  경영정보    20    20),
 ('컴퓨터공학',
            학번   이름     학과  Quiz  중간고사
  4  201722222   지민  컴퓨터공학    18    16
  3  201611111  다니엘  컴퓨터공학    17    18)]

## Numpy 기초연습문제

In [19]:
import numpy as np #import 함수로 numpy불러오기

1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [20]:
a = np.zeros((3, 4)) 
# numpy 배열을 만드는 방법 :zeros()는 해당 배열에 모두 0을 집어 넣는다. (행,열) 
# np.zeros()함수는 괄호 안에 쓴 숫자 개수만큼의 '0' 공간을 만들어 줌

a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [21]:
for i in range(a.shape[0]):#numpy.shape(): 배열의 크기를 알려준다. a.shape[0]=3 -->행
    for j in range(a.shape[1]): #numpy.shape[1]=4-->열
        
        a[i, j] = i*4 + j + 1 #i는 4씩 곱해지며 j는 1씩 더해지는 리스트 구성.
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [22]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1 # 위와 같다만 num은 1을 배정해줌으로써 1부터 +1씩 반복되게 만들어놓음.
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오

In [23]:
a[1, 2] # 0부터 순서가 시작하기 때문에 1 콤마 2임

7.0

4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

array([[5., 6., 7., 8.]])

In [24]:
a.shape #shape 행열(차원)확인,다차원 배열의 차원과 그룹 안의 원소들의 크기를 확인할 때 array.shape 함수를 사용

(3, 4)

In [25]:
a[[1], :] #둘째 행 전체 출력, shape에 indexing 을 적용하면 차원, 원소 크기를 각 각 선택해서 반환

array([[5., 6., 7., 8.]])

5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.
    
    array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

In [36]:
a[:,[1, 2]] # 둘째열과 셋째열 행 전체 출력

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

array([1., 2., 3., 4., 5., 6.])

In [27]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6]) 
# NumPy (Numerical Python)로 ndarray :fast, 공간 효율적 벡터 연산가능 다차원 배열을 만들 수 있다. 그중 하나가 array들.
# asarray나 array나 비슷한데, 차이가 있다면 array는 copy=true가 기본이고, asarray는 copy=false가 기본이다 = 옵션을 명시하지 않으면 array는 복사본을 만들어서 저장하고, asarray는 복사본없이 저장
result

array([1., 2., 3., 4., 5., 6.])

In [28]:
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [29]:
b = np.random.random((3, 4)) #.random함수 : 0이상 1미만함수를 무작위로 돌려줌. (행, 열)
b

array([[0.18833947, 0.75267658, 0.40499979, 0.50900718],
       [0.16817349, 0.31502725, 0.39909452, 0.53428974],
       [0.09404418, 0.6292535 , 0.99071503, 0.55425376]])

8. a와 b의 요소곱을 하여 c에 저장하시오.

In [30]:
c = a * b
c

array([[ 0.18833947,  1.50535316,  1.21499937,  2.03602874],
       [ 0.84086747,  1.89016351,  2.79366162,  4.27431794],
       [ 0.84639761,  6.29253502, 10.89786528,  6.65104509]])

9. b의 전치행렬을 구하여 d에 저장하시오.

In [31]:
d = b.T #.T :행과 열을 바꾸기
d

array([[0.18833947, 0.16817349, 0.09404418],
       [0.75267658, 0.31502725, 0.6292535 ],
       [0.40499979, 0.39909452, 0.99071503],
       [0.50900718, 0.53428974, 0.55425376]])

In [32]:
d.shape # .shape: 차원의 크기를 알려줌 (4개의 행 3개의 열)

(4, 3)

10. a와 d에 대하여 각 차원의 크기를 출력하시오.


In [33]:
print(a.shape, d.shape)

(3, 4) (4, 3)


11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [34]:
e = a.dot(d) #.dot : numpy array를 곱할때 사용
e

array([[ 4.94472075,  4.13267052,  6.54171129],
       [12.36481286,  9.79901053, 15.61477715],
       [19.78490498, 15.46535055, 24.687843  ]])

12. e에 대하여 각 열의 합을 계산하시오.

In [35]:
np.sum(e, axis=1) #,sum= 합

array([15.61910255, 37.77860054, 59.93809853])