In [6]:
import pandas as pd
import numpy as np

In [7]:
# 코드로 방정식 표현하기
coefficient_matrix = [[2, 2, 1], [2, -1, 2], [1, -1, 2]]
constant_vector = [9,6,5]

In [8]:
#array creation
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [9]:
test_array = np.array([1, 4, 5, "8"], float) #String Type의 데이터를 입력해도
print(test_array)
print(type(test_array[3])) #Float Type으로 자동 형변환을 실시
print(test_array.dtype) #Array(배열)	전체의 데이터 Type을 반환함
print(test_array.shape) #Array(배열)	의 shape을 반환함

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [10]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [11]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [12]:
np.array(tensor, int).ndim

3

In [13]:
np.array(tensor, int).size

48

In [17]:
np.array([[1,2,3],[4.5, 5, 6]],dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype=np.float32).nbytes

24

In [22]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype=np.int8).nbytes

6

In [23]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype=np.float64).nbytes

48

In [24]:
test_matrix =[[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [25]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [26]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [27]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

In [29]:
test_matrix =[[1,2,3,4],[1,2,5,8],[[1,2,3,4],[1,2,5,8]]]
np.array(test_matrix).flatten()

array([list([1, 2, 3, 4]), list([1, 2, 5, 8]),
       list([[1, 2, 3, 4], [1, 2, 5, 8]])], dtype=object)

In [30]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)
print(a)
print(a[0,0]) # Two dimensional array representation #1
print(a[0][0]) # Two dimensional array representation #2
a[0,0] = 12 # Matrix 0,0 에 12 할당
print(a)
a[0][0] = 5 # Matrix 0,0 에 12 할당
print(a)

[[1 2 3]
 [4 5 6]]
1
1
[[12  2  3]
 [ 4  5  6]]
[[5 2 3]
 [4 5 6]]


In [32]:
test_example = np.array([[1,2,3],[4.5,5,6]],int)
test_example 

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
test_example[0][0]

1

In [34]:
test_example[0,0]

1

In [35]:
test_example[0,0] = 12
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [36]:
test_example[0][0] = 5
test_example[0,0]

5

In [37]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
a[:,2:] # 전체 Row의 2열 이상
a[1,1:3] # 1 Row의 1열 ~ 2열
a[1:3] # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

In [38]:
test_exmaple = np.array([
    [1, 2, 5, 8], [1, 2, 5, 8],[1, 2, 5, 8],[1, 2, 5, 8]], int)
test_exmaple[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [39]:
test_exmaple[:,1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [40]:
test_exmaple[1,:2]

array([1, 2])

In [41]:
test_exmaple = np.array([
    [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_exmaple[:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])